/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as clerk from "../clerk.js";
import type * as countries from "../countries.js";
import type * as documents from "../documents.js";
import type * as entityLabels from "../entityLabels.js";
import type * as events from "../events.js";
import type * as grades from "../grades.js";
import type * as http from "../http.js";
import type * as labels from "../labels.js";
import type * as notes from "../notes.js";
import type * as notifications from "../notifications.js";
import type * as projects from "../projects.js";
import type * as studentSubjects from "../studentSubjects.js";
import type * as subjects from "../subjects.js";
import type * as tasks from "../tasks.js";
import type * as users from "../users.js";
import type * as util from "../util.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  clerk: typeof clerk;
  countries: typeof countries;
  documents: typeof documents;
  entityLabels: typeof entityLabels;
  events: typeof events;
  grades: typeof grades;
  http: typeof http;
  labels: typeof labels;
  notes: typeof notes;
  notifications: typeof notifications;
  projects: typeof projects;
  studentSubjects: typeof studentSubjects;
  subjects: typeof subjects;
  tasks: typeof tasks;
  users: typeof users;
  util: typeof util;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
