import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner"
import { Inter } from "next/font/google";
import { NavBar } from "@/components/containers/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <NavBar />
        {children}
        <Toaster />
      </body>
      
    </html>
  );
}
